### PR TITLE
Added Swift subspec

### PR DESCRIPTION
**Pull request by bre7**
I know you thought about it (#30) but since it was only one file you didn't add it to the sepc.
I think it's simpler to allow devs to use ChameleonFramework/Swift in their podfiles instead of asking them to download a separate file, etc.

(Thanks Cocoalumberjack for the subspec example)

### CODE REVIEW

**Comment by bre7** [comment]
Now it's working. I'll update the readme.

**Comment by ViccAlexander** [comment]
This is definitely cleaner. Appreciate the huge amount of time you've dedicated on improving this framework @bre7 :sunglasses: Quick question though, is there anything I'm required to do to get this working once I accept the pull request? Or will it work automatically?

**Comment by bre7** [comment]
Only push a new version of the spec (1.2.1?)

**Comment by bre7** [comment]
Now it's working...Forgot to add public to functions :laughing:

**Comment by ViccAlexander** [comment]
@bre7 Hmm it seems like you added support for osx, however UIKit is not available on osx. Upon removing that line, and running `pod lib lint` on the pod spec I seem to be getting the following error:

``` ruby
 -> ChameleonFramework (1.2.1)
    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS]  clang: error: linker command failed with exit code 1 (use -v to see invocation)

[!] ChameleonFramework did not pass validation.
You can use the `--no-clean` option to inspect any
```

Tried messing with it, but couldn't seem to find a solution. Any suggestions?

**Comment by bre7** [comment]
Ooops. I'll have a look later :)

**Comment by bre7** [comment]
PR in a sec the issue was this line:
```ruby
s.source_files ....
```
Since each subspec already defined the source files there were duplicated symbols

**Pull request merged**
