### PR TITLE
Carthage support

### LINKED ISSUE #37: Add Carthage support

### LINKED ISSUE #51: Wrong navigation bar color
The following line in AppDelegate makes navigationBar background and text color white. 
        `Chameleon.setGlobalThemeUsingPrimaryColor(FlatMint(), withSecondaryColor: FlatBlue(), andContentStyle: UIContentStyle.Contrast)`

### LINKED ISSUE #53: flatten bug
`color.flatten` calls `colorWithFlatVersionFrom(self)`, then `[color getLightness:nil valueForA:nil valueForB:nil alpha:&colorAlpha];`. Inside `getLightness` there's this code:
```objectivec
*L = [LABValues[0] floatValue];
*A = [LABValues[1] floatValue];
*B = [LABValues[2] floatValue];
```
but they are all nil

### LINKED ISSUE #57: EXC_BAD_ACCESS Error
I am getting an EXC_BAD_ACCESS error on the following line in UIColor+ChameleonPrivate:

        *L = [LABValues[0] floatValue];

(L = NULL)

Why is this? I installed manually, not with CocoaPods (I just dragged the files into my project and imported Chameleon.h - no other errors)

### PR DESCRIPTION
**Pull request by bre7**
xcodeproj added

Done.
* Fixes #37
* Fixes #51
* Fixes #53 
* Fixes #57
* Added Demo target
* Removed `flatify()` (as per https://github.com/ViccAlexander/Chameleon/issues/48#issuecomment-142133074)
* Added Carthage to README
* Added shields to README

### CODE REVIEW

**Comment by ViccAlexander** [comment]
Awesome! Let me know when you'd like me to merge it!

**Comment by bre7** [comment]
I think it's ok now.

**Comment by bre7** [comment]
Done.

Added demo and fixed #51, #53

**Comment by bre7** [comment]
Ready for merge

**Comment by ViccAlexander** [comment]
This is awesome thank you so much!

**Pull request merged**
