### PR TITLE
Added new methods for creating Analogous colors;

### PR DESCRIPTION
**Pull request by raymundcat**
I added two new methods that generate analogous(or adjacent) colors to a given flat color and returns them in an array. I find that these colors help with creating nice gradients and secondary colors.

### CODE REVIEW

**Comment by raymundcat** [comment]
here's a sample i did with the demo:
simulator screen shot 5 mar 2017 2 32 09 am

**Comment by bre7** [comment]
Hi ray(?), great idea 👍 One minor improvement: return analogous color BUT allow the user to specify whether it should be flat or not.

**Comment by raymundcat** [comment]
>Isn't it similar to Analogous color scheme?

oh you're right, totes similar. sorry about that, i should have been looking at the color schemes ^^ would you guys be open to adding more of these color harmonies in the color schemes library? http://www.tigercolor.com/color-lab/color-theory/color-harmonies.htm

**Comment by bre7** [comment]
Open a new issue asking for them, it's not my decision though

**Comment by raymundcat** [comment]
alright, will do. thanks Nathan ^^

**Comment by bre7** [comment]
👍

**Pull request closed without merging**
