### PR TITLE
Added primary Social Colors 

### PR DESCRIPTION
**Pull request by ohthatsjhall**
I am a huge fan of Chameleon and have used it in countless projects of mine. You have done an amazing job, I appreciate all the work you've done.

In a recent project I need to add a few social icons from popular social media sites, thus coming up with the idea to include the primary color from over 15 social media applications such twitter, facebook, snapchat, soundcloud, etc.

I simply added them to UIColor+Chameleon and also included them in the ChameleonShorthnad (being a swift developer myself). 

I hope you consider these changes useful and please let me know if you'd like me to make additional chnages for you. Thanks Vicc!

### CODE REVIEW

**Comment by bre7** [comment]
Quite useful, I'll leave It to Vic to merge it since he didn't want to add more colors but these are brand ones so maybe there's no problem. 
Would you mind removing DSStore files and rebasing ?

**Comment by ohthatsjhall** [comment]
Thanks again - I removed the DS_Store file

**Comment by bre7** [comment]
There's still `Pod/Classes/.DS_Store` and `Pod/.DS_Store` (add .DS_Store to your local .gitignore)

**Comment by ohthatsjhall** [comment]
Appreciate the instructions, if you can't tell, its my first contribution. Thanks again for the help, let me know if I can help with anything else.

**Comment by bre7** [comment]
No worries, that's one of the points of GH :P

It'll take a bit for @ViccAlexander to either merge or close this PR.

**Comment by bre7** [comment]
Yeah, by using a subspec.

@ohthatsjhall could you add the new colors to a separate file ? E.g: `UIColor+ChameleonSocialColors`

**Comment by ViccAlexander** [comment]
Perfect if @ohthatsjhall goes ahead and updates it we can merge it. Once I'm ready to update the pod spec I'll probably bother you for some help @bre7 😄

**Comment by bre7** [comment]
@ohthatsjhall could you submit a new PR with the colors, following the new format ? (Variable with function callback)

**Pull request closed without merging**
