### PR TITLE
Fixed colorWithFlatVersionFrom: sets colors with alpha = 0

### LINKED ISSUE #70: colorWithFlatVersionFrom: returns colors with alpha==0

### PR DESCRIPTION
**Pull request by wimbledon**
Closes #70

### CODE REVIEW

**Comment by bre7** [comment]
It doesn't set the alpha to 0, it get's the color's current alpha and computes a flat color taking said value into account instead of a hardcoded 1 (Similar to #50)

**Comment by wimbledon** [comment]
The problem is that it returns alpha==0.0f when I pass in a flatColor (i.e. FlatBlue) to getLightness: right now.
How would you recommend solving the bug #70?

**Comment by bre7** [comment]
```
[color getLightness:nil valueForA:nil valueForB:nil alpha:&colorAlpha];
colorAlpha = colorAlpha > 0 ? colorAlpha : 1.0;
return [[self class] colorWithFlatVersionOf:color withAlpha:colorAlpha];
```

**Comment by bre7** [comment]
Thanks

**Comment by ViccAlexander** [comment]
@bre7 Yup. Just bumped it up to 2.0.4.

**Pull request merged**
